./image_convert.py empty.png
./image_convert.py passage.png
./image_convert.py box.png
./image_convert.py player_0.png
./image_convert.py player_1.png
./image_convert.py wall.png
./image_convert.py passageWithTarget.png
./image_convert.py boxOnTarget.png
./image_convert.py playerOnTarget_0.png
./image_convert.py playerOnTarget_1.png
